name: "semantic-kitti"

label_name_mapping:
  0: 'unlabeled'
  #################################################################################3
  1: 'outlier'
  10: 'car'
  11: 'bicycle'
  13: 'bus'
  15: 'motorcycle'
  16: 'on-rails'
  18: 'truck'
  20: 'other-vehicle'
  30: 'person'
  31: 'bicyclist'
  32: 'motorcyclist'
  40: 'road'
  44: 'parking'
  48: 'sidewalk'
  49: 'other-ground'
  50: 'building'
  51: 'fence'
  52: 'other-structure'
  60: 'lane-marking'
  70: 'vegetation'
  71: 'trunk'
  72: 'terrain'
  80: 'pole'
  81: 'traffic-sign'
  99: 'other-object'
  #################################################################################3
  252: 'moving-car'
  253: 'moving-bicyclist'
  254: 'moving-person'
  255: 'moving-motorcyclist'
  256: 'moving-on-rails'
  257: 'moving-bus'
  258: 'moving-truck'
  259: 'moving-other-vehicle'

kept_labels:
  - 'road'
  - 'sidewalk'
  - 'parking'
  - 'other-ground'
  - 'building'
  - 'car'
  - 'truck'
  - 'bicycle'
  - 'motorcycle'
  - 'other-vehicle'
  - 'vegetation'
  - 'trunk'
  - 'terrain'
  - 'person'
  - 'bicyclist'
  - 'motorcyclist'
  - 'fence'
  - 'pole'
  - 'traffic-sign'


voxel_size: 0.05 # m
range_size:
  - 64 # H
  - 2048 # W
sample_stride: 1
max_voxels: 84000

split:
  train:
#    - '00'
#    - '01'
#    - '02'
#    - '03'
    - '04'
#    - '05'
#    - '06'
#    - '07'
#    - '09'
#    - '10'

  valid:
    - '08'

  test:
    - '11'
    - '12'
    - '13'
    - '14'
    - '15'
    - '16'
    - '17'
    - '18'
    - '19'
    - '20'
    - '21'